apiVersion: apps/v1
kind: Deployment
metadata:
  name: logrctx-backend
  namespace: log-reduce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logrctx-backend
  template:
    metadata:
      labels:
        app: logrctx-backend
    spec:
      containers:
      - name: backend
        image: gd03/logrctx-web:backend
        env:
        - name: LOKI_URL
          value: "http://loki-loki-distributed-query-frontend.default:3100/loki/api/v1/query_range"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: logrctx-backend
  namespace: log-reduce
spec:
  selector:
    app: logrctx-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logrctx-frontend
  namespace: log-reduce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logrctx-frontend
  template:
    metadata:
      labels:
        app: logrctx-frontend
    spec:
      containers:
      - name: frontend
        image: gd03/logrctx-web:frontend
        env:
        - name: VITE_API_URL
          value: "http://logrctx-backend:8000/reduce"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: logrctx-frontend
  namespace: log-reduce
spec:
  selector:
    app: logrctx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
