# logrctx-frontend -> logrctx-frontend-headless -> logrctx.swiggy.prod
# logrctx-backend -> logrctx-backend-headless -> logrctx-api.swiggy.prod:8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logrctx-backend
  namespace: log-reduce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logrctx-backend
  template:
    metadata:
      labels:
        app: logrctx-backend
    spec:
      containers:
      - name: backend
        image: gd03/logrctx-web:backend
        env:
        - name: LOKI_URL
          value: "http://loki-loki-distributed-query-frontend.default:3100/loki/api/v1/query_range"
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: logrctx-backend-headless
  namespace: log-reduce
  annotations:
    external-dns.alpha.kubernetes.io/hostname: logrctx-api.swiggy.prod
    external-dns.alpha.kubernetes.io/ttl: "5"
spec:
  clusterIP: None
  selector:
    app: logrctx-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logrctx-frontend
  namespace: log-reduce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logrctx-frontend
  template:
    metadata:
      labels:
        app: logrctx-frontend
    spec:
      containers:
      - name: frontend
        image: gd03/logrctx-web:frontend
        env:
        - name: VITE_API_URL
          value: "https://logrctx-api.swiggyops.de/reduce"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: logrctx-frontend-headless
  namespace: log-reduce
  annotations:
    external-dns.alpha.kubernetes.io/hostname: logrctx.swiggy.prod
    external-dns.alpha.kubernetes.io/ttl: "5"
spec:
  clusterIP: None
  selector:
    app: logrctx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

